AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: Imgur Subreddit Cache

Resources:
  SubtopicAPI:
    Type: AWS::Serverless::Api
    Name: subtopicAPI
    Properties:
      StageName: Dev
      DefinitionBody: {}
      CacheClusterEnabled: true
      CacheClusterSize: "1.6"
#      Cors:
#        AllowMethods: "'*'"
#        AllowHeaders: "'*'"
#        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: 2.0
        info:
          title: Imgur Subtopic
        paths:
          /{subreddit}:
            get:
              parameters:
                - name: "subreddit"
                  in: "path"
                  required: true
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub:
                    - arn:aws:apigateway:us-east-1:lambda:path/functions/${FunctionArn}/invocations
                    - { FunctionArn: !GetAtt GetSubtopic.Arn }
                httpMethod: GET
                type: aws_proxy
        definitions:
          Empty:
            type: object
            title: Empty Schema
  GetSubtopic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.yajac.imgur.handler.ImgurCacheReadHandler
#      CodeUri: ./target/ImgurTopicCache-1.0.jar
      Runtime: java8
      Timeout: 20
      MemorySize: 512
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{subreddit}
            Method: GET
            RestApiId: !Ref SubtopicAPI

#  CacheSubTopic:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: org.yajac.imgur.handler.ImgurCacheWriteHandler
#      Runtime: java8
#      Timeout: 30
#      MemorySize: 512
#      Role:
#        Fn::ImportValue:
#          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
#      Events:
#        PutEvent:
#          Type: Api
#          Properties:
#            Path: /{subreddit}
#            Method: put